import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ConvexClientProvider from './ConvexClientProvider';
import PrivyWrapper from './PrivyWrapper';
import OnboardingWrapper from './OnboardingWrapper';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <ConvexClientProvider>
          <PrivyWrapper>
            <OnboardingWrapper>{children}</OnboardingWrapper>
          </PrivyWrapper>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
